###########################################################################################################################################################################################
######################################################################### DATASET SPLITS FOR DSST REGRESSION ######################################################################
###########################################################################################################################################################################################

# DSST data splits - adjust these numbers based on your actual dataset size
# Format: from your create_dataset.py, you'll have train_X_test_Y directories
dsst_custom:
  - train: 19420
    test: 4855 
    batch_size: 256

gf_custom:
  - train: 27181
    test: 6796 
    batch_size: 256