###################################################################################################################################################################################
######################################################################### DATASET SPLITS FOR CUSTOM DATASETS ######################################################################
###################################################################################################################################################################################
custom:
  - train: 148 
    test: 40 
    batch_size: 32
  - train: 320 
    test: 80 
    batch_size: 32
  - train: 480 
    test: 120 
    batch_size: 32
  - train: 1000 
    test: 100 
    batch_size: 32
  - train: 1600 
    test: 400 
    batch_size: 32
  - train: 1650 
    test: 495 
    batch_size: 32
  - train: 1725 
    test: 525 
    batch_size: 32
  - train: 3200 
    test: 700 
    batch_size: 32
  - train: 3400 
    test: 900 
    batch_size: 32
