#################################################################################################################################################################################################
######################################################################### RUN SETTINGS FOR POSITIONAL DESCRIPTORS DATASETS ######################################################################
#################################################################################################################################################################################################
lrs:
  custom:
    - 0.1 
    - 0.01 
    - 0.005 
    - 0.001 
    - 0.0001
epochs:
  custom:
    - 500
    - 500
    - 500
    - 500
    - 500
runs:
  custom:
    - 3
    - 3
    - 3
    - 3
    - 3
