#################################################################################################################################################################################################
######################################################################### RUN SETTINGS FOR DSST REGRESSION DATASET ######################################################################
#################################################################################################################################################################################################

lrs:
  dsst_custom:
    - 0.01
    - 0.005
    - 0.001
    - 0.0005
    - 0.0001

epochs:
  dsst_custom:
    - 200
    - 300
    - 500
    - 500
    - 800

# Number of runs for statistical significance
runs:
  dsst_custom:
    - 5
    - 5
    - 3
    - 3
    - 3